os:
  - linux
  - osx
  - windows

language: rust

rust:
  - stable

jobs:
  fast_finish: true

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

script:
  - cargo test --verbose --all
  - cargo build --release --verbose --all

before_deploy:
  - ARCH=$(RUSTC_BOOTSTRAP=1 rustc -Z unstable-options --print target-spec-json | grep llvm-target | cut -d ":" -f2 | sed -E 's:("|,| +)::g' | sed 's:macosx.*:darwin:')
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install zip && BINARY="fs-tool.exe"; else BINARY="fs-tool"; fi
  - export TAR=$ARCH.tar.gz && export ZIP=$ARCH.zip && export BUILD_FILE="target/release/${BINARY}"
  - tar cvzf "$TAR" $BUILD_FILE
  - zip "$ZIP" $BUILD_FILE

deploy:
  provider: releases
  api_key:
    secure: pTp1GveByknwXupSWQ5jMLzYjb4n/mfLdLD3HhEQrOvFv9KwG+eFjbxfF3SowXgacyZ/brU4Lh1QiYLnxf9LZlUUgouIbB9j/ZIe2bs+byQ/7zQ1gC0v273iqrOP23hoZFZkSypkW+Ysjb2GmoqdVdJd+Vq0MhzLq6SISgILIhQ64mmLQmjl2tmNOEa7zWIhSVRa5XW1tRwt4mOfWh7sK/Up/8gWCmkaYPDT2JjSi1KCpkr4t3/+ISZQCjtlhidkQntoyfrIiT+HPmvwwHGbSITxRBHqHnkfgmb0lTvErg3FW6pyFn0UTyjxWsEIodSBxvT3ibYtnEQk5lWWTqmWjRzWsVpdWlaUV6ffCucSM0tb+HvJTwJisc1VAcGNfxloNR3ER4nu7lAfikrLOu4oHHKhegfeEukQgSXwiCXAi5d8qO1dpmH/OAhPLw2qYfvVOuITxx6zK1LN2HcK+KWNG8xie+uElWDKFhgpw9d6z02Pz8yqPdvuCJKcftgDulEW962duYOU4uazCoAFm9p/48PA87eqHg3HjLG4KUr1HJixoBeZBIX/jncp85PjTTLzMhOv4fD0asAVdwIVic/vEw/ilYFjxgxl1VpYxVzTOsOCxm6VBPy9jYMwIR8TCXhed5IuPutV5HMTswxrwgwgRrl4+QdBNnp2v1gV/h0F7wQ=
  file: 
    - "$TAR"
    - "$ZIP"
  on:
    tags: true
    repo: bjohnnyd/fs-tool
  skip_cleanup: 'true'
