[package]
name = "fs-tool"
version = "0.1.1"
authors = ["Johnny Debebe <28043284+bjohnnyd@users.noreply.github.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
reqwest = "0.10.0-alpha.2"
scraper = "0.11.0"
tokio = { version = "0.2.0-alpha.6", features = ["macros"]}
structopt = "0.3.5"
